'use client';

import { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Send, 
  Sparkles, 
  Image as ImageIcon, 
  FileText, 
  Mic,
  Bot,
  User,
  Loader2,
  Wand2,
  RefreshCw
} from 'lucide-react';
import SectionHeading from '@/components/ui/SectionHeading';

type Message = {
  id: number;
  type: 'user' | 'ai';
  content: string;
  timestamp: Date;
};

const samplePrompts = [
  "Explain quantum computing in simple terms",
  "Write a poem about artificial intelligence",
  "What are the benefits of machine learning?",
  "How can AI help my business grow?",
];

const aiResponses: Record<string, string> = {
  "explain quantum computing in simple terms": "Quantum computing is like having a super-powered calculator that can explore many possibilities at once! 🚀\n\nTraditional computers use bits (0s and 1s), but quantum computers use 'qubits' that can be both 0 AND 1 simultaneously. This means they can solve complex problems exponentially faster.\n\nImagine finding a book in a library: a regular computer checks each book one by one, while a quantum computer checks all books at the same time!",
  "write a poem about artificial intelligence": "🎭 **The Digital Mind**\n\nIn circuits deep where data flows,\nA new kind of thinking grows.\nNot of flesh, but silicon bright,\nLearning patterns day and night.\n\nFrom chaos, order does emerge,\nAs algorithms gently surge.\nA partner in our human quest,\nTo build, to dream, to be our best.\n\n— Generated by Arian AI ✨",
  "what are the benefits of machine learning?": "📊 **Key Benefits of Machine Learning:**\n\n• **Automation** - Reduce manual tasks by 70%\n• **Accuracy** - Up to 99% prediction accuracy\n• **Speed** - Process data 1000x faster\n• **Insights** - Discover hidden patterns\n• **Scalability** - Handle unlimited data volume\n• **Cost Savings** - Reduce operational costs by 40%\n\nAt Arian Data, we've helped clients achieve 3x ROI with our ML solutions!",
  "how can ai help my business grow?": "🚀 **AI Can Transform Your Business:**\n\n**1. Customer Experience**\n   • 24/7 intelligent chatbots\n   • Personalized recommendations\n\n**2. Operations**\n   • Automated workflows\n   • Predictive maintenance\n\n**3. Decision Making**\n   • Data-driven insights\n   • Risk assessment\n\n**4. Revenue Growth**\n   • Dynamic pricing\n   • Lead scoring\n\n📈 Our clients see an average 45% increase in efficiency!\n\nReady to start? Let's talk!",
};

export default function AIPlayground() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [activeTab, setActiveTab] = useState<'chat' | 'image' | 'document'>('chat');
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSend = async () => {
    if (!input.trim() || isTyping) return;

    const userMessage: Message = {
      id: Date.now(),
      type: 'user',
      content: input,
      timestamp: new Date(),
    };

    setMessages(prev => [...prev, userMessage]);
    setInput('');
    setIsTyping(true);

    // Simulate AI thinking
    await new Promise(resolve => setTimeout(resolve, 1500 + Math.random() * 1000));

    // Get AI response
    const normalizedInput = input.toLowerCase().trim();
    let response = aiResponses[normalizedInput];
    
    if (!response) {
      response = `🤖 Great question about "${input}"!\n\nAs an AI assistant, I can help with a wide range of topics including:\n\n• Data Analysis & Insights\n• Machine Learning Solutions\n• Process Automation\n• Business Intelligence\n\nFor a personalized answer, please contact our team at Arian Data. We'd love to discuss how AI can transform your specific needs!`;
    }

    const aiMessage: Message = {
      id: Date.now() + 1,
      type: 'ai',
      content: response,
      timestamp: new Date(),
    };

    setMessages(prev => [...prev, aiMessage]);
    setIsTyping(false);
  };

  const handlePromptClick = (prompt: string) => {
    setInput(prompt);
  };

  const resetChat = () => {
    setMessages([]);
    setInput('');
  };

  return (
    <section className="relative py-16 sm:py-20 lg:py-28 overflow-hidden">
      {/* Background */}
      <div className="absolute inset-0 bg-gradient-to-br from-primary-950 via-primary-900 to-black" />
      
      {/* Animated grid */}
      <div className="absolute inset-0 opacity-10">
        <div className="absolute inset-0" style={{
          backgroundImage: `radial-gradient(circle at center, rgba(255,255,255,0.1) 1px, transparent 1px)`,
          backgroundSize: '40px 40px'
        }} />
      </div>

      {/* Glowing orbs */}
      <motion.div
        animate={{ scale: [1, 1.3, 1], opacity: [0.3, 0.5, 0.3] }}
        transition={{ duration: 8, repeat: Infinity }}
        className="absolute top-20 left-1/4 w-64 h-64 bg-secondary-500/30 rounded-full blur-3xl"
      />
      <motion.div
        animate={{ scale: [1, 1.2, 1], opacity: [0.2, 0.4, 0.2] }}
        transition={{ duration: 10, repeat: Infinity, delay: 2 }}
        className="absolute bottom-20 right-1/4 w-80 h-80 bg-accent-cyan/20 rounded-full blur-3xl"
      />

      <div className="container-custom relative z-10">
        <SectionHeading
          label="Try It Live"
          title="AI Playground"
          description="Experience the power of our AI firsthand. Ask anything and see intelligent responses in real-time."
          light
        />

        {/* Main playground container */}
        <div className="max-w-4xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="bg-white/5 backdrop-blur-xl rounded-[2rem] border border-white/10 overflow-hidden shadow-2xl"
          >
            {/* Tabs */}
            <div className="flex items-center gap-2 p-4 border-b border-white/10">
              {[
                { id: 'chat', icon: Bot, label: 'AI Chat' },
                { id: 'image', icon: ImageIcon, label: 'Image AI' },
                { id: 'document', icon: FileText, label: 'Doc AI' },
              ].map((tab) => (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id as typeof activeTab)}
                  className={`flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-medium transition-all ${
                    activeTab === tab.id
                      ? 'bg-gradient-to-r from-secondary-500 to-accent-cyan text-white'
                      : 'text-gray-400 hover:text-white hover:bg-white/10'
                  }`}
                >
                  <tab.icon className="w-4 h-4" />
                  {tab.label}
                </button>
              ))}
              
              <div className="flex-1" />
              
              {messages.length > 0 && (
                <button
                  onClick={resetChat}
                  className="flex items-center gap-2 px-3 py-2 rounded-xl text-gray-400 hover:text-white hover:bg-white/10 transition-all text-sm"
                >
                  <RefreshCw className="w-4 h-4" />
                  Reset
                </button>
              )}
            </div>

            {/* Chat area */}
            <div className="h-[400px] overflow-y-auto p-4 sm:p-6 space-y-4">
              {messages.length === 0 ? (
                <div className="h-full flex flex-col items-center justify-center text-center">
                  <motion.div
                    initial={{ scale: 0.8, opacity: 0 }}
                    animate={{ scale: 1, opacity: 1 }}
                    className="w-20 h-20 rounded-3xl bg-gradient-to-br from-secondary-500 to-accent-cyan flex items-center justify-center mb-6"
                  >
                    <Wand2 className="w-10 h-10 text-white" />
                  </motion.div>
                  <h3 className="text-xl font-bold text-white mb-2">Start a Conversation</h3>
                  <p className="text-gray-400 mb-6 max-w-md">
                    Ask our AI anything about technology, business, or just have a creative conversation.
                  </p>
                  
                  {/* Sample prompts */}
                  <div className="flex flex-wrap justify-center gap-2">
                    {samplePrompts.map((prompt, index) => (
                      <motion.button
                        key={prompt}
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: index * 0.1 }}
                        onClick={() => handlePromptClick(prompt)}
                        className="px-4 py-2 rounded-full bg-white/10 text-sm text-gray-300 hover:bg-white/20 hover:text-white transition-all"
                      >
                        {prompt}
                      </motion.button>
                    ))}
                  </div>
                </div>
              ) : (
                <>
                  <AnimatePresence>
                    {messages.map((message) => (
                      <motion.div
                        key={message.id}
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        className={`flex gap-3 ${message.type === 'user' ? 'justify-end' : 'justify-start'}`}
                      >
                        {message.type === 'ai' && (
                          <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-secondary-500 to-accent-cyan flex items-center justify-center flex-shrink-0">
                            <Sparkles className="w-4 h-4 text-white" />
                          </div>
                        )}
                        <div
                          className={`max-w-[80%] p-4 rounded-2xl ${
                            message.type === 'user'
                              ? 'bg-gradient-to-r from-primary-700 to-primary-800 text-white'
                              : 'bg-white/10 text-gray-200'
                          }`}
                        >
                          <p className="text-sm whitespace-pre-line">{message.content}</p>
                        </div>
                        {message.type === 'user' && (
                          <div className="w-8 h-8 rounded-lg bg-primary-700 flex items-center justify-center flex-shrink-0">
                            <User className="w-4 h-4 text-white" />
                          </div>
                        )}
                      </motion.div>
                    ))}
                  </AnimatePresence>
                  
                  {isTyping && (
                    <motion.div
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      className="flex gap-3"
                    >
                      <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-secondary-500 to-accent-cyan flex items-center justify-center">
                        <Sparkles className="w-4 h-4 text-white" />
                      </div>
                      <div className="bg-white/10 p-4 rounded-2xl">
                        <div className="flex gap-1">
                          {[0, 1, 2].map((i) => (
                            <motion.div
                              key={i}
                              animate={{ scale: [1, 1.3, 1] }}
                              transition={{ duration: 0.6, repeat: Infinity, delay: i * 0.2 }}
                              className="w-2 h-2 bg-secondary-400 rounded-full"
                            />
                          ))}
                        </div>
                      </div>
                    </motion.div>
                  )}
                </>
              )}
              <div ref={messagesEndRef} />
            </div>

            {/* Input area */}
            <div className="p-4 border-t border-white/10">
              <form
                onSubmit={(e) => {
                  e.preventDefault();
                  handleSend();
                }}
                className="flex gap-3"
              >
                <div className="flex-1 relative">
                  <input
                    type="text"
                    value={input}
                    onChange={(e) => setInput(e.target.value)}
                    placeholder="Ask anything..."
                    disabled={isTyping}
                    className="w-full px-5 py-3 pr-12 rounded-2xl bg-white/10 border border-white/10 text-white placeholder:text-gray-500 focus:outline-none focus:border-secondary-500 transition-colors disabled:opacity-50"
                  />
                  <button
                    type="button"
                    className="absolute right-3 top-1/2 -translate-y-1/2 p-1.5 rounded-lg text-gray-500 hover:text-white hover:bg-white/10 transition-colors"
                  >
                    <Mic className="w-5 h-5" />
                  </button>
                </div>
                <button
                  type="submit"
                  disabled={!input.trim() || isTyping}
                  className="px-5 py-3 rounded-2xl bg-gradient-to-r from-secondary-500 to-accent-cyan text-white font-semibold hover:shadow-lg hover:shadow-secondary-500/25 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
                >
                  {isTyping ? (
                    <Loader2 className="w-5 h-5 animate-spin" />
                  ) : (
                    <Send className="w-5 h-5" />
                  )}
                </button>
              </form>
              <p className="text-center text-xs text-gray-500 mt-3">
                Powered by Arian AI • Try asking about AI, ML, or business automation
              </p>
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  );
}
